---
kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
    name: pvc-nfs-dynamic-volumes
spec:
    storageClassName: nfs-csi-dynamic
    accessModes: 
        - ReadWriteMany 
    resources: 
        requests: 
            storage: 1Gi
    
    
