
--- 
apiVersion: v1 
kind: PersistentVolume 
metadata: 
    name: nfs-static-volume1 
spec: 
    capacity:
        storage: 1Gi 
    accessModes: 
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: nfs-csi-static
    mountOptions: 
        - hard 
        - nolock 
        - nfsvers=4.1 
    csi: 
        driver: nfs.csi.k8s.io
        readOnly: false 
        volumeHandle: volumeid-static-volume1 # make sure it's a unique id in the cluster 
        volumeAttributes: 
            server: server.nfs
            share: /var/nfs/kube_static/volume1
